# Generated by Django 4.0.3 on 2023-10-19 15:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Describe what this job category is about', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('staff_number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
                ('position', models.CharField(choices=[('DIR', 'Director'), ('GM', 'General Manager'), ('MGR', 'Manager'), ('ENG', 'Electrical Engineer'), ('TEN', 'Technician Engineer')], help_text='Select your position', max_length=3)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Substation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('station_code', models.CharField(max_length=10)),
                ('region', models.CharField(choices=[('ae', 'Accra East'), ('aw', 'Accra West'), ('v', 'Volta'), ('ase', 'Ashanti East'), ('asw', 'Ashanti West'), ('ass', 'Ashanti South'), ('e', 'Eastern'), ('w', 'Western'), ('t', 'Tema'), ('c', 'Central'), ('po', 'Projects Office'), ('sta', 'Subtransmission Accra'), ('stk', 'Subtransmission Ashanti')], help_text='Select region where station is found', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(null=True)),
                ('region', models.CharField(choices=[('ae', 'Accra East'), ('aw', 'Accra West'), ('v', 'Volta'), ('ase', 'Ashanti East'), ('asw', 'Ashanti West'), ('ass', 'Ashanti South'), ('e', 'Eastern'), ('w', 'Western'), ('t', 'Tema'), ('c', 'Central'), ('po', 'Projects Office'), ('sta', 'Subtransmission Accra'), ('stk', 'Subtransmission Ashanti')], help_text='Select region where job was done', max_length=3)),
                ('job_description', models.TextField(help_text='Describe the work done in detail', max_length=1000)),
                ('job_status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed')], help_text='Select the status of the job', max_length=1)),
                ('remarks', models.CharField(max_length=500)),
                ('equipment', models.ForeignKey(help_text='Select equipment on which was done', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mtcereports.equipment')),
                ('job_category', models.ForeignKey(help_text='Select the category of job', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mtcereports.jobcategory')),
                ('personnel', models.ManyToManyField(help_text='Select personnel involved in the job', to='mtcereports.personnel')),
                ('substation', models.ForeignKey(help_text='Select substation where work was done', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mtcereports.substation')),
            ],
        ),
    ]
