# Generated by Django 4.0.3 on 2023-11-07 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mtcereports', '0006_alter_job_job_description_alter_personnel_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthcontainer',
            name='month_name',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], help_text='Select month', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='monthcontainer',
            unique_together={('year_name', 'month_name', 'author')},
        ),
    ]
