# Generated by Django 4.0.3 on 2023-12-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtcereports', '0007_alter_monthcontainer_month_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthcontainer',
            options={'ordering': ['month_name', 'year_name']},
        ),
        migrations.AlterUniqueTogether(
            name='monthcontainer',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
