# Generated by Django 4.0.3 on 2023-12-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtcereports', '0008_alter_monthcontainer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanExtractPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_extract', 'Can extract data')],
            },
        ),
    ]
