# Generated by Django 4.0.3 on 2024-07-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtcereports', '0009_canextractpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='region',
            field=models.CharField(choices=[('a', 'Accra'), ('ae', 'Accra East'), ('aw', 'Accra West'), ('v', 'Volta'), ('as', 'Ashanti'), ('ase', 'Ashanti East'), ('asw', 'Ashanti West'), ('ass', 'Ashanti South'), ('e', 'Eastern'), ('w', 'Western'), ('t', 'Tema'), ('c', 'Central'), ('po', 'Projects Office'), ('sta', 'Subtransmission Accra'), ('stk', 'Subtransmission Ashanti')], help_text='Select region where job was done', max_length=3),
        ),
        migrations.AlterField(
            model_name='substation',
            name='region',
            field=models.CharField(choices=[('a', 'Accra'), ('ae', 'Accra East'), ('aw', 'Accra West'), ('v', 'Volta'), ('as', 'Ashanti'), ('ase', 'Ashanti East'), ('asw', 'Ashanti West'), ('ass', 'Ashanti South'), ('e', 'Eastern'), ('w', 'Western'), ('t', 'Tema'), ('c', 'Central'), ('po', 'Projects Office'), ('sta', 'Subtransmission Accra'), ('stk', 'Subtransmission Ashanti')], help_text='Select region where station is found', max_length=3),
        ),
        migrations.AlterField(
            model_name='substation',
            name='station_code',
            field=models.CharField(max_length=50),
        ),
    ]
